/*
 * SPDX-FileCopyrightText: 2026 - Sebastian Ritter <bastie@users.noreply.github.com>
 * SPDX-License-Identifier: MIT
 */

extension javax.swing.event {

  /// Listener for `UndoableEditEvent`s.
  ///
  /// Register with a `javax.swing.text.Document` (or any other source) to
  /// receive notification whenever an undoable edit occurs.
  ///
  /// - Since: Java 1.2
  @MainActor
  public protocol UndoableEditListener: AnyObject {

    /// Called whenever an undoable edit is generated by the source.
    func undoableEditHappened(_ e: javax.swing.event.UndoableEditEvent)
  }
}
