/*
 * SPDX-FileCopyrightText: 2026 - Sebastian Ritter <bastie@users.noreply.github.com>
 * SPDX-License-Identifier: MIT
 */

import Foundation

// MARK: - java.util.stream.LongStream

extension java.util.stream {

  /// A sequence of primitive `Int64`-valued elements (Java's `long`) supporting
  /// sequential aggregate operations.
  ///
  /// Mirrors `java.util.stream.LongStream` (Java 8). See ``IntStream`` for the
  /// shared lazy, single-use pipeline design this specialises.
  ///
  /// - Since: Java 8
  public final class LongStream: @unchecked Sendable {

    private let _makeSequence: () -> AnySequence<Int64>
    nonisolated(unsafe) private var _isParallel: Bool = false

    // MARK: - Internal constructors

    init<S: Sequence>(_ sequence: S) where S.Element == Int64 {
      let captured = AnySequence(sequence)
      _makeSequence = { captured }
    }

    private init(_ factory: @escaping () -> AnySequence<Int64>, isParallel: Bool = false) {
      _makeSequence = factory
      _isParallel = isParallel
    }

    // MARK: - Factory methods

    /// Returns a stream containing the given elements.
    /// - Since: Java 8
    public static func of(_ elements: Int64...) -> LongStream { LongStream(elements) }

    /// Returns an empty stream.
    /// - Since: Java 8
    public static func empty() -> LongStream { LongStream(EmptyCollection<Int64>()) }

    /// Returns a stream of `startInclusive, startInclusive+1, …, endExclusive-1`.
    /// - Since: Java 8
    public static func range(_ startInclusive: Int64, _ endExclusive: Int64) -> LongStream {
      guard startInclusive < endExclusive else { return .empty() }
      return LongStream(startInclusive..<endExclusive)
    }

    /// Returns a stream of `startInclusive, startInclusive+1, …, endInclusive`.
    /// - Since: Java 8
    public static func rangeClosed(_ startInclusive: Int64, _ endInclusive: Int64) -> LongStream {
      guard startInclusive <= endInclusive else { return .empty() }
      return LongStream(startInclusive...endInclusive)
    }

    /// Returns an infinite sequential stream where each element is generated by `supplier`.
    /// - Since: Java 8
    public static func generate(_ supplier: java.util.function.LongSupplier) -> LongStream {
      LongStream(AnySequence(sequence(state: (), next: { _ in supplier.get() })))
    }

    /// Returns an infinite sequential ordered stream: `seed, f(seed), f(f(seed)), …`.
    /// - Since: Java 8
    public static func iterate(_ seed: Int64, _ f: java.util.function.LongUnaryOperator) -> LongStream {
      LongStream(AnySequence(sequence(first: seed, next: { f.apply($0) })))
    }

    /// Returns a finite sequential ordered stream that begins with `seed` and
    /// continues applying `f` as long as `hasNext` holds for the current value.
    /// - Since: Java 9
    public static func iterate(
      _ seed: Int64,
      _ hasNext: java.util.function.LongPredicate,
      _ f: java.util.function.LongUnaryOperator
    ) -> LongStream {
      LongStream({
        var results: [Int64] = []
        var current = seed
        while hasNext.test(current) {
          results.append(current)
          current = f.apply(current)
        }
        return AnySequence(results)
      })
    }

    /// Concatenates two streams into one, elements of `a` followed by elements of `b`.
    /// - Since: Java 8
    public static func concat(_ a: LongStream, _ b: LongStream) -> LongStream {
      LongStream({ AnySequence(Array(a._makeSequence()) + Array(b._makeSequence())) })
    }

    // MARK: - Intermediate operations

    /// Returns a stream consisting of the elements that match `predicate`.
    /// - Since: Java 8
    public func filter(_ predicate: java.util.function.LongPredicate) -> LongStream {
      LongStream({ [_makeSequence] in
        AnySequence(_makeSequence().lazy.filter { predicate.test($0) })
      }, isParallel: _isParallel)
    }

    /// Returns a stream consisting of the results of applying `mapper` to each element.
    /// - Since: Java 8
    public func map(_ mapper: java.util.function.LongUnaryOperator) -> LongStream {
      LongStream({ [_makeSequence] in
        AnySequence(_makeSequence().lazy.map { mapper.apply($0) })
      }, isParallel: _isParallel)
    }

    /// Returns an object-valued `Stream` consisting of the results of applying `mapper`.
    /// - Since: Java 8
    public func mapToObj<R>(_ mapper: java.util.function.LongFunction<R>) -> java.util.stream.Stream<R> {
      java.util.stream.Stream<R>(_makeSequence().lazy.map { mapper.apply($0) })
    }

    /// Returns an `IntStream` consisting of the results of applying `mapper` (narrowing).
    /// - Since: Java 8
    public func mapToInt(_ mapper: java.util.function.LongToIntFunction) -> java.util.stream.IntStream {
      java.util.stream.IntStream(_makeSequence().lazy.map { mapper.apply($0) })
    }

    /// Returns a `DoubleStream` consisting of the results of applying `mapper`.
    /// - Since: Java 8
    public func mapToDouble(_ mapper: java.util.function.LongToDoubleFunction) -> java.util.stream.DoubleStream {
      java.util.stream.DoubleStream(_makeSequence().lazy.map { mapper.apply($0) })
    }

    /// Returns a stream consisting of the results of replacing each element
    /// with the contents of the stream produced by `mapper`.
    /// - Since: Java 8
    public func flatMap(_ mapper: java.util.function.LongFunction<LongStream>) -> LongStream {
      LongStream({ [_makeSequence] in
        AnySequence(_makeSequence().lazy.flatMap { mapper.apply($0)._makeSequence() })
      }, isParallel: _isParallel)
    }

    /// Returns a stream consisting of the distinct elements.
    ///
    /// This is a **stateful** intermediate operation.
    /// - Since: Java 8
    public func distinct() -> LongStream {
      LongStream({ [_makeSequence] in
        var seen = Set<Int64>()
        return AnySequence(_makeSequence().lazy.filter { seen.insert($0).inserted })
      }, isParallel: _isParallel)
    }

    /// Returns a stream consisting of the elements sorted in natural order.
    ///
    /// This is a **stateful** intermediate operation.
    /// - Since: Java 8
    public func sorted() -> LongStream {
      LongStream({ [_makeSequence] in AnySequence(Array(_makeSequence()).sorted()) }, isParallel: _isParallel)
    }

    /// Returns a stream consisting of the elements, additionally performing
    /// `action` on each element as they are consumed by the pipeline.
    /// - Since: Java 8
    public func peek(_ action: java.util.function.LongConsumer) -> LongStream {
      LongStream({ [_makeSequence] in
        AnySequence(_makeSequence().lazy.map { element -> Int64 in
          action.accept(element)
          return element
        })
      }, isParallel: _isParallel)
    }

    /// Returns a stream truncated to no more than `maxSize` elements.
    /// - Since: Java 8
    public func limit(_ maxSize: Int64) -> LongStream {
      LongStream({ [_makeSequence] in AnySequence(_makeSequence().prefix(Int(maxSize))) }, isParallel: _isParallel)
    }

    /// Returns a stream that discards the first `n` elements.
    /// - Since: Java 8
    public func skip(_ n: Int64) -> LongStream {
      LongStream({ [_makeSequence] in AnySequence(_makeSequence().dropFirst(Int(n))) }, isParallel: _isParallel)
    }

    /// Returns an object-valued `Stream` boxing each `Int64` element.
    /// - Since: Java 8
    public func boxed() -> java.util.stream.Stream<Int64> {
      java.util.stream.Stream<Int64>(_makeSequence())
    }

    /// Returns a `DoubleStream` widening each `Int64` element to `Double`.
    /// - Since: Java 8
    public func asDoubleStream() -> java.util.stream.DoubleStream {
      java.util.stream.DoubleStream(_makeSequence().lazy.map { Double($0) })
    }

    /// Returns this stream with parallel execution enabled for terminal operations.
    /// - Since: Java 8
    @discardableResult
    public func parallel() -> LongStream { _isParallel = true; return self }

    /// Returns this stream with parallel execution disabled.
    /// - Since: Java 8
    @discardableResult
    public func sequential() -> LongStream { _isParallel = false; return self }

    /// Returns `true` if this stream will execute terminal operations in parallel.
    /// - Since: Java 8
    public func isParallel() -> Bool { _isParallel }

    // MARK: - Terminal operations

    /// Performs `action` for each element of this stream.
    /// - Since: Java 8
    public func forEach(_ action: java.util.function.LongConsumer) {
      #if os(WASI)
      for element in _makeSequence() { action.accept(element) }
      #else
      if _isParallel {
        let elements = Array(_makeSequence())
        DispatchQueue.concurrentPerform(iterations: elements.count) { i in action.accept(elements[i]) }
      } else {
        for element in _makeSequence() { action.accept(element) }
      }
      #endif
    }

    /// Performs `action` for each element in encounter order.
    /// - Since: Java 8
    public func forEachOrdered(_ action: java.util.function.LongConsumer) {
      for element in _makeSequence() { action.accept(element) }
    }

    /// Returns the elements of this stream as a Swift array.
    /// - Since: Java 8
    public func toArray() -> [Int64] { Array(_makeSequence()) }

    /// Performs a reduction on the elements using `identity` and `op`.
    /// - Since: Java 8
    public func reduce(_ identity: Int64, _ op: java.util.function.LongBinaryOperator) -> Int64 {
      var result = identity
      for element in _makeSequence() { result = op.apply(result, element) }
      return result
    }

    /// Performs a reduction using `op` with no identity value. `nil` if empty.
    /// - Since: Java 8
    public func reduce(_ op: java.util.function.LongBinaryOperator) -> Int64? {
      var result: Int64? = nil
      for element in _makeSequence() {
        if let r = result { result = op.apply(r, element) } else { result = element }
      }
      return result
    }

    /// Returns the sum of the elements. `0` for an empty stream.
    /// - Since: Java 8
    public func sum() -> Int64 {
      var total: Int64 = 0
      for element in _makeSequence() { total += element }
      return total
    }

    /// Returns the minimum element, or `nil` if the stream is empty.
    /// - Since: Java 8
    public func min() -> Int64? { _makeSequence().min() }

    /// Returns the maximum element, or `nil` if the stream is empty.
    /// - Since: Java 8
    public func max() -> Int64? { _makeSequence().max() }

    /// Returns the count of elements in this stream.
    /// - Since: Java 8
    public func count() -> Int64 {
      var c: Int64 = 0
      for _ in _makeSequence() { c += 1 }
      return c
    }

    /// Returns the arithmetic mean of the elements, or `nil` if the stream is empty.
    /// - Since: Java 8
    public func average() -> Double? {
      var total: Int64 = 0
      var n = 0
      for element in _makeSequence() { total += element; n += 1 }
      guard n > 0 else { return nil }
      return Double(total) / Double(n)
    }

    /// Returns `true` if any element matches `predicate`.
    /// - Since: Java 8
    public func anyMatch(_ predicate: java.util.function.LongPredicate) -> Bool {
      for element in _makeSequence() { if predicate.test(element) { return true } }
      return false
    }

    /// Returns `true` if all elements match `predicate`, or the stream is empty.
    /// - Since: Java 8
    public func allMatch(_ predicate: java.util.function.LongPredicate) -> Bool {
      for element in _makeSequence() { if !predicate.test(element) { return false } }
      return true
    }

    /// Returns `true` if no elements match `predicate`, or the stream is empty.
    /// - Since: Java 8
    public func noneMatch(_ predicate: java.util.function.LongPredicate) -> Bool {
      for element in _makeSequence() { if predicate.test(element) { return false } }
      return true
    }

    /// Returns the first element of this stream, or `nil` if empty.
    /// - Since: Java 8
    public func findFirst() -> Int64? {
      for element in _makeSequence() { return element }
      return nil
    }

    /// Returns any element of this stream, or `nil` if empty.
    /// - Since: Java 8
    public func findAny() -> Int64? { findFirst() }

    /// Returns an iterator over the elements of this stream.
    /// - Since: Java 8
    public func iterator() -> any java.util.Iterator<Int64> {
      _LongArrayIterator(toArray())
    }

    /// Returns a `Spliterator` over the elements of this stream.
    /// - Since: Java 8
    public func spliterator() -> any java.util.Spliterator<Int64> {
      _ArraySpliterator(toArray())
    }
  }
}

// MARK: - Internal array-backed Iterator

private final class _LongArrayIterator<E>: java.util.Iterator, IteratorProtocol {
  public typealias Element = E
  private let _elements: [E]
  private var _index: Int = 0
  init(_ elements: [E]) { _elements = elements }
  public func hasNext() -> Bool { _index < _elements.count }
  public func next() throws(java.lang.RuntimeException) -> E {
    guard _index < _elements.count else { throw java.util.NoSuchElementException() }
    defer { _index += 1 }
    return _elements[_index]
  }
  public func next() -> E? {
    guard _index < _elements.count else { return nil }
    defer { _index += 1 }
    return _elements[_index]
  }
  public func remove() throws(java.lang.RuntimeException) {
    throw java.lang.IllegalStateException("remove() not supported on a stream-backed iterator")
  }
  public func makeIterator() -> _LongArrayIterator<E> { self }
}
